#!/bin/bash
#
# Perform necessary mcollective removal steps
# after package is uninstalled.
#

is_smartos()
{
  uname -v | grep ^joyent 2>&1>/dev/null
}

if is_smartos; then
    PREFIX="/opt/local"
else
    PREFIX="/usr"
fi

# `if` cargo culted from omnibus-chef
if [ ! -e /etc/redhat-release -o "x$1" == "x0" ]; then
  rm -f $PREFIX/bin/mco
  rm -f $PREFIX/bin/mcollectived
fi

echo "mcollective has been uninstalled!"

exit 0
